# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@inquirer/figures-1.0.3" = {
      name = "_at_inquirer_slash_figures";
      packageName = "@inquirer/figures";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@inquirer/figures/-/figures-1.0.3.tgz";
        sha512 = "ErXXzENMH5pJt5/ssXV0DfWUZqly8nGzf0UcBV9xTnP+KyffE2mqyxIMBrZ8ijQck2nU0TQm40EQB53YreyWHw==";
      };
    };
    "@ljharb/through-2.3.13" = {
      name = "_at_ljharb_slash_through";
      packageName = "@ljharb/through";
      version = "2.3.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ljharb/through/-/through-2.3.13.tgz";
        sha512 = "/gKJun8NNiWGZJkGzI/Ragc53cOdcLNdzjLaIa+GEjguQs0ulsurx8WN0jijdK9yPqDvziX995sMRLyLt1uZMQ==";
      };
    };
    "@pnpm/config.env-replace-1.1.0" = {
      name = "_at_pnpm_slash_config.env-replace";
      packageName = "@pnpm/config.env-replace";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@pnpm/config.env-replace/-/config.env-replace-1.1.0.tgz";
        sha512 = "htyl8TWnKL7K/ESFa1oW2UB5lVDxuF5DpM7tBi6Hu2LNL3mWkIzNLG6N4zoCUP1lCKNxWy/3iu8mS8MvToGd6w==";
      };
    };
    "@pnpm/network.ca-file-1.0.2" = {
      name = "_at_pnpm_slash_network.ca-file";
      packageName = "@pnpm/network.ca-file";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@pnpm/network.ca-file/-/network.ca-file-1.0.2.tgz";
        sha512 = "YcPQ8a0jwYU9bTdJDpXjMi7Brhkr1mXsXrUJvjqM2mQDgkRiz8jFaQGOdaLxgjtUfQgZhKy/O3cG/YwmgKaxLA==";
      };
    };
    "@pnpm/npm-conf-2.2.2" = {
      name = "_at_pnpm_slash_npm-conf";
      packageName = "@pnpm/npm-conf";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@pnpm/npm-conf/-/npm-conf-2.2.2.tgz";
        sha512 = "UA91GwWPhFExt3IizW6bOeY/pQ0BkuNwKjk9iQW9KqxluGCrg4VenZ0/L+2Y0+ZOtme72EVvg6v0zo3AMQRCeA==";
      };
    };
    "@sindresorhus/is-5.6.0" = {
      name = "_at_sindresorhus_slash_is";
      packageName = "@sindresorhus/is";
      version = "5.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sindresorhus/is/-/is-5.6.0.tgz";
        sha512 = "TV7t8GKYaJWsn00tFDqBw8+Uqmr8A0fRU1tvTQhyZzGv0sJCGRQL3JGMI3ucuKo3XIZdUP+Lx7/gh2t3lewy7g==";
      };
    };
    "@szmarczak/http-timer-5.0.1" = {
      name = "_at_szmarczak_slash_http-timer";
      packageName = "@szmarczak/http-timer";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@szmarczak/http-timer/-/http-timer-5.0.1.tgz";
        sha512 = "+PmQX0PiAYPMeVYe237LJAYvOMYW1j2rH5YROyS3b4CTVJum34HfRvKvAzozHAQG0TnHNdUfY9nCeUyRAs//cw==";
      };
    };
    "@tootallnate/quickjs-emscripten-0.23.0" = {
      name = "_at_tootallnate_slash_quickjs-emscripten";
      packageName = "@tootallnate/quickjs-emscripten";
      version = "0.23.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tootallnate/quickjs-emscripten/-/quickjs-emscripten-0.23.0.tgz";
        sha512 = "C5Mc6rdnsaJDjO3UpGW/CQTHtCKaYlScZTly4JIu97Jxo/odCiH0ITnDXSJPTOrEKk/ycSZ0AOgTmkDtkOsvIA==";
      };
    };
    "@types/http-cache-semantics-4.0.4" = {
      name = "_at_types_slash_http-cache-semantics";
      packageName = "@types/http-cache-semantics";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/http-cache-semantics/-/http-cache-semantics-4.0.4.tgz";
        sha512 = "1m0bIFVc7eJWyve9S0RnuRgcQqF/Xd5QsUZAZeQFr1Q3/p9JWoQQEqmVy+DPTNpGXwhgIetAoYF8JSc33q29QA==";
      };
    };
    "agent-base-7.1.1" = {
      name = "agent-base";
      packageName = "agent-base";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/agent-base/-/agent-base-7.1.1.tgz";
        sha512 = "H0TSyFNDMomMNJQBn8wFV5YC/2eJ+VXECwOadZJT554xP6cODZHPX3H9QMQECxvrgiSOP1pHjy1sMWQVYJOUOA==";
      };
    };
    "ajv-8.16.0" = {
      name = "ajv";
      packageName = "ajv";
      version = "8.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-8.16.0.tgz";
        sha512 = "F0twR8U1ZU67JIEtekUcLkXkoO5mMMmgGD8sK/xUFzJ805jxHQl92hImFAqqXMyMYjSPOyUPAwHYhB72g5sTXw==";
      };
    };
    "ajv-formats-2.1.1" = {
      name = "ajv-formats";
      packageName = "ajv-formats";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv-formats/-/ajv-formats-2.1.1.tgz";
        sha512 = "Wx0Kx52hxE7C18hkMEggYlEifqWZtYaRgouJor+WMdPnQyEK13vgEWyVNup7SoeeoLMsr4kf5h6dOW11I15MUA==";
      };
    };
    "ansi-align-3.0.1" = {
      name = "ansi-align";
      packageName = "ansi-align";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-align/-/ansi-align-3.0.1.tgz";
        sha512 = "IOfwwBF5iczOjp/WeY4YxyjqAFMQoZufdQWDd19SEExbVLNXqvpzSJ/M7Za4/sCPmQ0+GRquoA7bGcINcxew6w==";
      };
    };
    "ansi-escapes-4.3.2" = {
      name = "ansi-escapes";
      packageName = "ansi-escapes";
      version = "4.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-escapes/-/ansi-escapes-4.3.2.tgz";
        sha512 = "gKXj5ALrKWQLsYG9jlTRmR/xKluxHV+Z9QEwNIgCfM1/uwPMCuzVVnh5mwTd+OuBZcwSIMbqssNWRm1lE51QaQ==";
      };
    };
    "ansi-escapes-6.2.1" = {
      name = "ansi-escapes";
      packageName = "ansi-escapes";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-escapes/-/ansi-escapes-6.2.1.tgz";
        sha512 = "4nJ3yixlEthEJ9Rk4vPcdBRkZvQZlYyu8j4/Mqz5sgIkddmEnH2Yj2ZrnP9S3tQOvSNRUIgVNF/1yPpRAGNRig==";
      };
    };
    "ansi-regex-5.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
        sha512 = "quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
      };
    };
    "ansi-regex-6.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-6.0.1.tgz";
        sha512 = "n5M855fKb2SsfMIiFFoVrABHJC8QtHwVx+mHWP3QcEqBHYienj5dHSgjbxtC0WEZXYt4wcD6zrQElDPhFuZgfA==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "ansi-styles-6.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-6.2.1.tgz";
        sha512 = "bN798gFfQX+viw3R7yrGWRqnrN2oRkEkUjjl4JNn4E8GxxbjtG3FbrEIIY3l8/hrwUwIeCZvi4QuOTP4MErVug==";
      };
    };
    "ast-types-0.13.4" = {
      name = "ast-types";
      packageName = "ast-types";
      version = "0.13.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/ast-types/-/ast-types-0.13.4.tgz";
        sha512 = "x1FCFnFifvYDDzTaLII71vG5uvDwgtmDTEVWAxrgeiR8VjMONcCXJx7E+USjDtHlwFmt9MysbqgF9b9Vjr6w+w==";
      };
    };
    "atomically-2.0.3" = {
      name = "atomically";
      packageName = "atomically";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/atomically/-/atomically-2.0.3.tgz";
        sha512 = "kU6FmrwZ3Lx7/7y3hPS5QnbJfaohcIul5fGqf7ok+4KklIEk9tJ0C2IQPdacSbVUWv6zVHXEBWoWd6NrVMT7Cw==";
      };
    };
    "base64-js-1.5.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.5.1.tgz";
        sha512 = "AKpaYlHn8t4SVbOHCy+b5+KKgvR4vrsD8vbvrbiQJps7fKDTkjkDry6ji0rUJjC0kzbNePLwzxq8iypo41qeWA==";
      };
    };
    "basic-ftp-5.0.5" = {
      name = "basic-ftp";
      packageName = "basic-ftp";
      version = "5.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/basic-ftp/-/basic-ftp-5.0.5.tgz";
        sha512 = "4Bcg1P8xhUuqcii/S0Z9wiHIrQVPMermM1any+MX5GeGD7faD3/msQUDGLol9wOcz4/jbg/WJnGqoJF6LiBdtg==";
      };
    };
    "bl-4.1.0" = {
      name = "bl";
      packageName = "bl";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bl/-/bl-4.1.0.tgz";
        sha512 = "1W07cM9gS6DcLperZfFSj+bWLtaPGSOHWhPiGzXmvVJbRLdG82sH/Kn8EtW1VqWVA54AKf2h5k5BbnIbwF3h6w==";
      };
    };
    "boxen-7.1.1" = {
      name = "boxen";
      packageName = "boxen";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boxen/-/boxen-7.1.1.tgz";
        sha512 = "2hCgjEmP8YLWQ130n2FerGv7rYpfBmnmp9Uy2Le1vge6X3gZIfSmEzP5QTDElFxcvVcXlEn8Aq6MU/PZygIOog==";
      };
    };
    "buffer-5.7.1" = {
      name = "buffer";
      packageName = "buffer";
      version = "5.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-5.7.1.tgz";
        sha512 = "EHcyIPBQ4BSGlvjB16k5KgAJ27CIsHY/2JBmCRReo48y9rQ3MaUzWX3KVlBa4U7MyX02HdVj0K7C3WaB3ju7FQ==";
      };
    };
    "cacheable-lookup-7.0.0" = {
      name = "cacheable-lookup";
      packageName = "cacheable-lookup";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cacheable-lookup/-/cacheable-lookup-7.0.0.tgz";
        sha512 = "+qJyx4xiKra8mZrcwhjMRMUhD5NR1R8esPkzIYxX96JiecFoxAXFuz/GpR3+ev4PE1WamHip78wV0vcmPQtp8w==";
      };
    };
    "cacheable-request-10.2.14" = {
      name = "cacheable-request";
      packageName = "cacheable-request";
      version = "10.2.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/cacheable-request/-/cacheable-request-10.2.14.tgz";
        sha512 = "zkDT5WAF4hSSoUgyfg5tFIxz8XQK+25W/TLVojJTMKBaxevLBBtLxgqguAuVQB8PVW79FVjHcU+GJ9tVbDZ9mQ==";
      };
    };
    "call-bind-1.0.7" = {
      name = "call-bind";
      packageName = "call-bind";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bind/-/call-bind-1.0.7.tgz";
        sha512 = "GHTSNSYICQ7scH7sZ+M2rFopRoLh8t2bLSW6BbgrtLsahOIB5iyAVJf9GjWK3cYTDaMj4XdBpM1cA6pIS0Kv2w==";
      };
    };
    "camelcase-7.0.1" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-7.0.1.tgz";
        sha512 = "xlx1yCK2Oc1APsPXDL2LdlNP6+uu8OCDdhOBSVT279M/S+y75O30C2VuD8T2ogdePBBl7PfPF4504tnLgX3zfw==";
      };
    };
    "chalk-4.1.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.2.tgz";
        sha512 = "oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==";
      };
    };
    "chalk-5.3.0" = {
      name = "chalk";
      packageName = "chalk";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-5.3.0.tgz";
        sha512 = "dLitG79d+GV1Nb/VYcCDFivJeK1hiukt9QjRNVOsUtTy1rR1YJsmpGGTZ3qJos+uw7WmWF4wUwBd9jxjocFC2w==";
      };
    };
    "chardet-0.7.0" = {
      name = "chardet";
      packageName = "chardet";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chardet/-/chardet-0.7.0.tgz";
        sha512 = "mT8iDcrh03qDGRRmoA2hmBJnxpllMR+0/0qlzjqZES6NdiWDcZkCNAk4rPFZ9Q85r27unkiNNg8ZOiwZXBHwcA==";
      };
    };
    "cli-boxes-3.0.0" = {
      name = "cli-boxes";
      packageName = "cli-boxes";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-boxes/-/cli-boxes-3.0.0.tgz";
        sha512 = "/lzGpEWL/8PfI0BmBOPRwp0c/wFNX1RdUML3jK/RcSBA9T8mZDdQpqYBKtCFTOfQbwPqWEOpjqW+Fnayc0969g==";
      };
    };
    "cli-cursor-3.1.0" = {
      name = "cli-cursor";
      packageName = "cli-cursor";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-cursor/-/cli-cursor-3.1.0.tgz";
        sha512 = "I/zHAwsKf9FqGoXM4WWRACob9+SNukZTd94DWF57E4toouRulbCxcUh6RKUEOQlYTHJnzkPMySvPNaaSLNfLZw==";
      };
    };
    "cli-cursor-4.0.0" = {
      name = "cli-cursor";
      packageName = "cli-cursor";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-cursor/-/cli-cursor-4.0.0.tgz";
        sha512 = "VGtlMu3x/4DOtIUwEkRezxUZ2lBacNJCHash0N0WeZDBS+7Ux1dm3XWAgWYxLJFMMdOeXMHXorshEFhbMSGelg==";
      };
    };
    "cli-spinners-2.9.2" = {
      name = "cli-spinners";
      packageName = "cli-spinners";
      version = "2.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-spinners/-/cli-spinners-2.9.2.tgz";
        sha512 = "ywqV+5MmyL4E7ybXgKys4DugZbX0FC6LnwrhjuykIjnK9k8OQacQ7axGKnjDXWNhns0xot3bZI5h55H8yo9cJg==";
      };
    };
    "cli-width-4.1.0" = {
      name = "cli-width";
      packageName = "cli-width";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-width/-/cli-width-4.1.0.tgz";
        sha512 = "ouuZd4/dm2Sw5Gmqy6bGyNNNe1qt9RpmxveLSO7KcgsTnU7RXfsw+/bukWGo1abgBiMAic068rclZsO4IWmmxQ==";
      };
    };
    "clone-1.0.4" = {
      name = "clone";
      packageName = "clone";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone/-/clone-1.0.4.tgz";
        sha512 = "JQHZ2QMW6l3aH/j6xCqQThY/9OH4D/9ls34cgkUBiEeocRTU04tHfKPBsUK1PqZCUQM7GiA0IIXJSuXHI64Kbg==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "conf-12.0.0" = {
      name = "conf";
      packageName = "conf";
      version = "12.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/conf/-/conf-12.0.0.tgz";
        sha512 = "fIWyWUXrJ45cHCIQX+Ck1hrZDIf/9DR0P0Zewn3uNht28hbt5OfGUq8rRWsxi96pZWPyBEd0eY9ama01JTaknA==";
      };
    };
    "config-chain-1.1.13" = {
      name = "config-chain";
      packageName = "config-chain";
      version = "1.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/config-chain/-/config-chain-1.1.13.tgz";
        sha512 = "qj+f8APARXHrM0hraqXYb2/bOVSV4PvJQlNZ/DVj0QrmNM2q2euizkeuVckQ57J+W0mRH6Hvi+k50M4Jul2VRQ==";
      };
    };
    "configstore-6.0.0" = {
      name = "configstore";
      packageName = "configstore";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/configstore/-/configstore-6.0.0.tgz";
        sha512 = "cD31W1v3GqUlQvbBCGcXmd2Nj9SvLDOP1oQ0YFuLETufzSPaKp11rYBsSOm7rCsW3OnIRAFM3OxRhceaXNYHkA==";
      };
    };
    "cross-spawn-7.0.3" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "7.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.3.tgz";
        sha512 = "iRDPJKUPVEND7dHPO8rkbOnPpyDygcDFtWjpeWNCgy8WP2rXcxXL8TskReQl6OrB2G7+UJrags1q15Fudc7G6w==";
      };
    };
    "crypto-random-string-4.0.0" = {
      name = "crypto-random-string";
      packageName = "crypto-random-string";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crypto-random-string/-/crypto-random-string-4.0.0.tgz";
        sha512 = "x8dy3RnvYdlUcPOjkEHqozhiwzKNSq7GcPuXFbnyMOCHxX8V3OgIg/pYuabl2sbUPfIJaeAQB7PMOK8DFIdoRA==";
      };
    };
    "data-uri-to-buffer-4.0.1" = {
      name = "data-uri-to-buffer";
      packageName = "data-uri-to-buffer";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/data-uri-to-buffer/-/data-uri-to-buffer-4.0.1.tgz";
        sha512 = "0R9ikRb668HB7QDxT1vkpuUBtqc53YyAwMwGeUFKRojY/NWKvdZ+9UYtRfGmhqNbRkTSVpMbmyhXipFFv2cb/A==";
      };
    };
    "data-uri-to-buffer-6.0.2" = {
      name = "data-uri-to-buffer";
      packageName = "data-uri-to-buffer";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/data-uri-to-buffer/-/data-uri-to-buffer-6.0.2.tgz";
        sha512 = "7hvf7/GW8e86rW0ptuwS3OcBGDjIi6SZva7hCyWC0yYry2cOPmLIjXAUHI6DK2HsnwJd9ifmt57i8eV2n4YNpw==";
      };
    };
    "debounce-fn-5.1.2" = {
      name = "debounce-fn";
      packageName = "debounce-fn";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/debounce-fn/-/debounce-fn-5.1.2.tgz";
        sha512 = "Sr4SdOZ4vw6eQDvPYNxHogvrxmCIld/VenC5JbNrFwMiwd7lY/Z18ZFfo+EWNG4DD9nFlAujWAo/wGuOPHmy5A==";
      };
    };
    "debug-4.3.5" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.5.tgz";
        sha512 = "pt0bNEmneDIvdL1Xsd9oDQ/wrQRkXDT4AUWlNZNPKvW5x/jyO9VFXkJUP07vQ2upmw5PlaITaPKc31jK13V+jg==";
      };
    };
    "decompress-response-6.0.0" = {
      name = "decompress-response";
      packageName = "decompress-response";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress-response/-/decompress-response-6.0.0.tgz";
        sha512 = "aW35yZM6Bb/4oJlZncMH2LCoZtJXTRxES17vE3hoRiowU2kWHaJKFkSBDnDR+cm9J+9QhXmREyIfv0pji9ejCQ==";
      };
    };
    "deep-extend-0.6.0" = {
      name = "deep-extend";
      packageName = "deep-extend";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-extend/-/deep-extend-0.6.0.tgz";
        sha512 = "LOHxIOaPYdHlJRtCQfDIVZtfw/ufM8+rVj649RIHzcm/vGwQRXFt6OPqIFWsm2XEMrNIEtWR64sY1LEKD2vAOA==";
      };
    };
    "defaults-1.0.4" = {
      name = "defaults";
      packageName = "defaults";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/defaults/-/defaults-1.0.4.tgz";
        sha512 = "eFuaLoy/Rxalv2kr+lqMlUnrDWV+3j4pljOIJgLIhI058IQfWJ7vXhyEIHu+HtC738klGALYxOKDO0bQP3tg8A==";
      };
    };
    "defer-to-connect-2.0.1" = {
      name = "defer-to-connect";
      packageName = "defer-to-connect";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/defer-to-connect/-/defer-to-connect-2.0.1.tgz";
        sha512 = "4tvttepXG1VaYGrRibk5EwJd1t4udunSOVMdLSAL6mId1ix438oPwPZMALY41FCijukO1L0twNcGsdzS7dHgDg==";
      };
    };
    "define-data-property-1.1.4" = {
      name = "define-data-property";
      packageName = "define-data-property";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-data-property/-/define-data-property-1.1.4.tgz";
        sha512 = "rBMvIzlpA8v6E+SJZoo++HAYqsLrkg7MSfIinMPFhmkorw7X+dOXVJQs+QT69zGkzMyfDnIMN2Wid1+NbL3T+A==";
      };
    };
    "degenerator-5.0.1" = {
      name = "degenerator";
      packageName = "degenerator";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/degenerator/-/degenerator-5.0.1.tgz";
        sha512 = "TllpMR/t0M5sqCXfj85i4XaAzxmS5tVA16dqvdkMwGmzI+dXLXnw3J+3Vdv7VKw+ThlTMboK6i9rnZ6Nntj5CQ==";
      };
    };
    "dot-prop-6.0.1" = {
      name = "dot-prop";
      packageName = "dot-prop";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dot-prop/-/dot-prop-6.0.1.tgz";
        sha512 = "tE7ztYzXHIeyvc7N+hR3oi7FIbf/NIjVP9hmAt3yMXzrQ072/fpjGLx2GxNxGxUl5V73MEqYzioOMoVhGMJ5cA==";
      };
    };
    "dot-prop-8.0.2" = {
      name = "dot-prop";
      packageName = "dot-prop";
      version = "8.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/dot-prop/-/dot-prop-8.0.2.tgz";
        sha512 = "xaBe6ZT4DHPkg0k4Ytbvn5xoxgpG0jOS1dYxSOwAHPuNLjP3/OzN0gH55SrLqpx8cBfSaVt91lXYkApjb+nYdQ==";
      };
    };
    "eastasianwidth-0.2.0" = {
      name = "eastasianwidth";
      packageName = "eastasianwidth";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eastasianwidth/-/eastasianwidth-0.2.0.tgz";
        sha512 = "I88TYZWc9XiYHRQ4/3c5rjjfgkjhLyW2luGIheGERbNQ6OY7yTybanSpDXZa8y7VUP9YmDcYa+eyq4ca7iLqWA==";
      };
    };
    "emoji-regex-10.3.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "10.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-10.3.0.tgz";
        sha512 = "QpLs9D9v9kArv4lfDEgg1X/gN5XLnf/A6l9cs8SPZLRZR3ZkY9+kwIQTxm+fsSej5UMYGE8fdoaZVIBlqG0XTw==";
      };
    };
    "emoji-regex-8.0.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
        sha512 = "MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==";
      };
    };
    "emoji-regex-9.2.2" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "9.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-9.2.2.tgz";
        sha512 = "L18DaJsXSUk2+42pv8mLs5jJT2hqFkFE4j21wOmgbUqsZ2hL72NsUU785g9RXgo3s0ZNgVl42TiHp3ZtOv/Vyg==";
      };
    };
    "env-paths-3.0.0" = {
      name = "env-paths";
      packageName = "env-paths";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/env-paths/-/env-paths-3.0.0.tgz";
        sha512 = "dtJUTepzMW3Lm/NPxRf3wP4642UWhjL2sQxc+ym2YMj1m/H2zDNQOlezafzkHwn6sMstjHTwG6iQQsctDW/b1A==";
      };
    };
    "es-define-property-1.0.0" = {
      name = "es-define-property";
      packageName = "es-define-property";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-define-property/-/es-define-property-1.0.0.tgz";
        sha512 = "jxayLKShrEqqzJ0eumQbVhTYQM27CfT1T35+gCgDFoL82JLsXqTJ76zv6A0YLOgEnLUMvLzsDsGIrl8NFpT2gQ==";
      };
    };
    "es-errors-1.3.0" = {
      name = "es-errors";
      packageName = "es-errors";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-errors/-/es-errors-1.3.0.tgz";
        sha512 = "Zf5H2Kxt2xjTvbJvP2ZWLEICxA6j+hAmMzIlypy4xcBg1vKVnx89Wy0GbS+kf5cwCVFFzdCFh2XSCFNULS6csw==";
      };
    };
    "escape-goat-4.0.0" = {
      name = "escape-goat";
      packageName = "escape-goat";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-goat/-/escape-goat-4.0.0.tgz";
        sha512 = "2Sd4ShcWxbx6OY1IHyla/CVNwvg7XwZVoXZHcSu9w9SReNP1EzzD5T8NWKIR38fIqEns9kDWKUQTXXAmlDrdPg==";
      };
    };
    "escape-string-regexp-5.0.0" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-5.0.0.tgz";
        sha512 = "/veY75JbMK4j1yjvuUxuVsiS/hr/4iHs9FTT6cgTexxdE0Ly/glccBAkloH/DofkjRbZU3bnoj38mOmhkZ0lHw==";
      };
    };
    "escodegen-2.1.0" = {
      name = "escodegen";
      packageName = "escodegen";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escodegen/-/escodegen-2.1.0.tgz";
        sha512 = "2NlIDTwUWJN0mRPQOdtQBzbUHvdGY2P1VXSyU83Q3xKxM7WHX2Ql8dKq782Q9TgQUNOLEzEYu9bzLNj1q88I5w==";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "estraverse-5.3.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-5.3.0.tgz";
        sha512 = "MMdARuVEQziNTeJD8DgMqmhwR11BRQ/cBP+pLtYdSTnf3MIO8fFeiINEbX36ZdNlfU/7A9f3gUw49B3oQsvwBA==";
      };
    };
    "esutils-2.0.3" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.3.tgz";
        sha512 = "kVscqXk4OCp68SZ0dkgEKVi6/8ij300KBWTJq32P/dYeWTSwK41WyTxalN1eRmA5Z9UU/LX9D7FWSmV9SAYx6g==";
      };
    };
    "execa-8.0.1" = {
      name = "execa";
      packageName = "execa";
      version = "8.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/execa/-/execa-8.0.1.tgz";
        sha512 = "VyhnebXciFV2DESc+p6B+y0LjSm0krU4OgJN44qFAhBY0TJ+1V61tYD2+wHusZ6F9n5K+vl8k0sTy7PEfV4qpg==";
      };
    };
    "external-editor-3.1.0" = {
      name = "external-editor";
      packageName = "external-editor";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/external-editor/-/external-editor-3.1.0.tgz";
        sha512 = "hMQ4CX1p1izmuLYyZqLMO/qGNw10wSv9QDCPfzXfyFrOaCSSoRfqE1Kf1s5an66J5JZC62NewG+mK49jOCtQew==";
      };
    };
    "fast-deep-equal-3.1.3" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
        sha512 = "f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
      };
    };
    "fetch-blob-3.2.0" = {
      name = "fetch-blob";
      packageName = "fetch-blob";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fetch-blob/-/fetch-blob-3.2.0.tgz";
        sha512 = "7yAQpD2UMJzLi1Dqv7qFYnPbaPx7ZfFK6PiIxQ4PfkGPyNyl2Ugx+a/umUonmKqjhM4DnfbMvdX6otXq83soQQ==";
      };
    };
    "figures-5.0.0" = {
      name = "figures";
      packageName = "figures";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/figures/-/figures-5.0.0.tgz";
        sha512 = "ej8ksPF4x6e5wvK9yevct0UCXh8TTFlWGVLlgjZuoBH1HwjIfKE/IdL5mq89sFA7zELi1VhKpmtDnrs7zWyeyg==";
      };
    };
    "form-data-encoder-2.1.4" = {
      name = "form-data-encoder";
      packageName = "form-data-encoder";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data-encoder/-/form-data-encoder-2.1.4.tgz";
        sha512 = "yDYSgNMraqvnxiEXO4hi88+YZxaHC6QKzb5N84iRCTDeRO7ZALpir/lVmf/uXUhnwUr2O4HU8s/n6x+yNjQkHw==";
      };
    };
    "formdata-polyfill-4.0.10" = {
      name = "formdata-polyfill";
      packageName = "formdata-polyfill";
      version = "4.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/formdata-polyfill/-/formdata-polyfill-4.0.10.tgz";
        sha512 = "buewHzMvYL29jdeQTVILecSaZKnt/RJWjoZCF5OW60Z67/GmSLBkOFM7qh1PI3zFNtJbaZL5eQu1vLfazOwj4g==";
      };
    };
    "fs-extra-11.2.0" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "11.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-11.2.0.tgz";
        sha512 = "PmDi3uwK5nFuXh7XDTlVnS17xJS7vW36is2+w3xcv8SVxiB4NyATf4ctkVY5bkSjX0Y4nbvZCq1/EjtEyr9ktw==";
      };
    };
    "function-bind-1.1.2" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.2.tgz";
        sha512 = "7XHNxH7qX9xG5mIwxkhumTox/MIRNcOgDrxWsMt2pAr23WHp6MrRlN7FBSFpCpr+oVO0F744iUgR82nJMfG2SA==";
      };
    };
    "fuse.js-7.0.0" = {
      name = "fuse.js";
      packageName = "fuse.js";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fuse.js/-/fuse.js-7.0.0.tgz";
        sha512 = "14F4hBIxqKvD4Zz/XjDc3y94mNZN6pRv3U13Udo0lNLCWRBUsrMv2xwcF/y/Z5sV6+FQW+/ow68cHpm4sunt8Q==";
      };
    };
    "get-east-asian-width-1.2.0" = {
      name = "get-east-asian-width";
      packageName = "get-east-asian-width";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-east-asian-width/-/get-east-asian-width-1.2.0.tgz";
        sha512 = "2nk+7SIVb14QrgXFHcm84tD4bKQz0RxPuMT8Ag5KPOq7J5fEmAg0UbXdTOSHqNuHSU28k55qnceesxXRZGzKWA==";
      };
    };
    "get-intrinsic-1.2.4" = {
      name = "get-intrinsic";
      packageName = "get-intrinsic";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.2.4.tgz";
        sha512 = "5uYhsJH8VJBTv7oslg4BznJYhDoRI6waYCxMmCdnTrcCrHA/fCFKoTFz2JKKE0HdDFUF7/oQuhzumXJK7paBRQ==";
      };
    };
    "get-stream-6.0.1" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-6.0.1.tgz";
        sha512 = "ts6Wi+2j3jQjqi70w5AlN8DFnkSwC+MqmxEzdEALB2qXZYV3X/b1CTfgPLGJNMeAWxdPfU8FO1ms3NUfaHCPYg==";
      };
    };
    "get-stream-8.0.1" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "8.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-8.0.1.tgz";
        sha512 = "VaUJspBffn/LMCJVoMvSAdmscJyS1auj5Zulnn5UoYcY531UWmdwhRWkcGKnGU93m5HSXP9LP2usOryrBtQowA==";
      };
    };
    "get-uri-6.0.3" = {
      name = "get-uri";
      packageName = "get-uri";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-uri/-/get-uri-6.0.3.tgz";
        sha512 = "BzUrJBS9EcUb4cFol8r4W3v1cPsSyajLSthNkz5BxbpDcHN5tIrM10E2eNvfnvBn3DaT3DUgx0OpsBKkaOpanw==";
      };
    };
    "gitmoji-cli-9.4.0" = {
      name = "gitmoji-cli";
      packageName = "gitmoji-cli";
      version = "9.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/gitmoji-cli/-/gitmoji-cli-9.4.0.tgz";
        sha512 = "yqiYRSN0PEI8v9EJXn/euL+9keVpcvlCo87yc+M1m3zhP666oQ5/Ee0SdrexqAVmF5b/ZLsIaAntxB85Dt6H7g==";
      };
    };
    "global-dirs-3.0.1" = {
      name = "global-dirs";
      packageName = "global-dirs";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/global-dirs/-/global-dirs-3.0.1.tgz";
        sha512 = "NBcGGFbBA9s1VzD41QXDG+3++t9Mn5t1FpLdhESY6oKY4gYTFpX4wO3sqGUa0Srjtbfj3szX0RnemmrVRUdULA==";
      };
    };
    "gopd-1.0.1" = {
      name = "gopd";
      packageName = "gopd";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/gopd/-/gopd-1.0.1.tgz";
        sha512 = "d65bNlIadxvpb/A2abVdlqKqV563juRnZ1Wtk6s1sIR8uNsXR70xqIzVqxVf1eTqDunwT2MkczEeaezCKTZhwA==";
      };
    };
    "got-12.6.1" = {
      name = "got";
      packageName = "got";
      version = "12.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/got/-/got-12.6.1.tgz";
        sha512 = "mThBblvlAF1d4O5oqyvN+ZxLAYwIJK7bpMxgYqPD9okW0C3qm5FFn7k811QrcuEBwaogR3ngOFoCfs6mRv7teQ==";
      };
    };
    "graceful-fs-4.2.10" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.10.tgz";
        sha512 = "9ByhssR2fPVsNZj478qUUbKfmL0+t5BDVyjShtyZZLiK7ZDAArFFfopyOTj0M05wE2tJPisA4iTnnXl2YoPvOA==";
      };
    };
    "graceful-fs-4.2.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz";
        sha512 = "RbJ5/jmFcNNCcDV5o9eTnBLJ/HszWV0P73bc+Ff4nS/rJj+YaS6IGyiOL0VoBYX+l1Wrl3k63h/KrH+nhJ0XvQ==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "has-property-descriptors-1.0.2" = {
      name = "has-property-descriptors";
      packageName = "has-property-descriptors";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-property-descriptors/-/has-property-descriptors-1.0.2.tgz";
        sha512 = "55JNKuIW+vq4Ke1BjOTjM2YctQIvCT7GFzHwmfZPGo5wnrgkid0YQtnAleFSqumZm4az3n2BS+erby5ipJdgrg==";
      };
    };
    "has-proto-1.0.3" = {
      name = "has-proto";
      packageName = "has-proto";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-proto/-/has-proto-1.0.3.tgz";
        sha512 = "SJ1amZAJUiZS+PhsVLf5tGydlaVB8EdFpaSO4gmiUKUOxk8qzn5AIy4ZeJUmh22znIdk/uMAUT2pl3FxzVUH+Q==";
      };
    };
    "has-symbols-1.0.3" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.3.tgz";
        sha512 = "l3LCuF6MgDNwTDKkdYGEihYjt5pRPbEg46rtlmnSPlUbgmB8LOIrKJbYYFBSbnPaJexMKtiPO8hmeRjRz2Td+A==";
      };
    };
    "hasown-2.0.2" = {
      name = "hasown";
      packageName = "hasown";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hasown/-/hasown-2.0.2.tgz";
        sha512 = "0hJU9SCPvmMzIBdZFqNPXWa6dqh7WdH0cII9y+CyS8rG3nL48Bclra9HmKhVVUHyPWNH5Y7xDwAB7bfgSjkUMQ==";
      };
    };
    "http-cache-semantics-4.1.1" = {
      name = "http-cache-semantics";
      packageName = "http-cache-semantics";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-cache-semantics/-/http-cache-semantics-4.1.1.tgz";
        sha512 = "er295DKPVsV82j5kw1Gjt+ADA/XYHsajl82cGNQG2eyoPkvgUhX+nDIyelzhIWbbsXP39EHcI6l5tYs2FYqYXQ==";
      };
    };
    "http-proxy-agent-7.0.2" = {
      name = "http-proxy-agent";
      packageName = "http-proxy-agent";
      version = "7.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-proxy-agent/-/http-proxy-agent-7.0.2.tgz";
        sha512 = "T1gkAiYYDWYx3V5Bmyu7HcfcvL7mUrTWiM6yOfa3PIphViJ/gFPbvidQ+veqSOHci/PxBcDabeUNCzpOODJZig==";
      };
    };
    "http2-wrapper-2.2.1" = {
      name = "http2-wrapper";
      packageName = "http2-wrapper";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http2-wrapper/-/http2-wrapper-2.2.1.tgz";
        sha512 = "V5nVw1PAOgfI3Lmeaj2Exmeg7fenjhRUgz1lPSezy1CuhPYbgQtbQj4jZfEAEMlaL+vupsvhjqCyjzob0yxsmQ==";
      };
    };
    "https-proxy-agent-7.0.5" = {
      name = "https-proxy-agent";
      packageName = "https-proxy-agent";
      version = "7.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-7.0.5.tgz";
        sha512 = "1e4Wqeblerz+tMKPIq2EMGiiWW1dIjZOksyHWSUm1rmuvw/how9hBHZ38lAGj5ID4Ik6EdkOw7NmWPy6LAwalw==";
      };
    };
    "human-signals-5.0.0" = {
      name = "human-signals";
      packageName = "human-signals";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/human-signals/-/human-signals-5.0.0.tgz";
        sha512 = "AXcZb6vzzrFAUE61HnN4mpLqd/cSIwNQjtNWR0euPm6y0iqx3G4gOXaIDdtdDwZmhwe82LA6+zinmW4UBWVePQ==";
      };
    };
    "iconv-lite-0.4.24" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.24.tgz";
        sha512 = "v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA==";
      };
    };
    "ieee754-1.2.1" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.2.1.tgz";
        sha512 = "dcyqhDvX1C46lXZcVqCpK+FtMRQVdIMN6/Df5js2zouUsqG7I6sFxitIC+7KYK29KdXOLHdu9zL4sFnoVQnqaA==";
      };
    };
    "import-lazy-4.0.0" = {
      name = "import-lazy";
      packageName = "import-lazy";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-lazy/-/import-lazy-4.0.0.tgz";
        sha512 = "rKtvo6a868b5Hu3heneU+L4yEQ4jYKLtjpnPeUdK7h0yzXGmyBTypknlkCvHFBqfX9YlorEiMM6Dnq/5atfHkw==";
      };
    };
    "imurmurhash-0.1.4" = {
      name = "imurmurhash";
      packageName = "imurmurhash";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/imurmurhash/-/imurmurhash-0.1.4.tgz";
        sha512 = "JmXMZ6wuvDmLiHEml9ykzqO6lwFbof0GG4IkcGaENdCRDDmMVnny7s5HsIgHCbaq0w2MyPhDqkhTUgS2LU2PHA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "ini-1.3.8" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.8.tgz";
        sha512 = "JV/yugV2uzW5iMRSiZAyDtQd+nxtUnjeLt0acNdw98kKLrvuRVyB80tsREOE7yvGVgalhZ6RNXCmEHkUKBKxew==";
      };
    };
    "ini-2.0.0" = {
      name = "ini";
      packageName = "ini";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-2.0.0.tgz";
        sha512 = "7PnF4oN3CvZF23ADhA5wRaYEQpJ8qygSkbtTXWBeXWXmEVRXK+1ITciHWwHhsjv1TmW0MgacIv6hEi5pX5NQdA==";
      };
    };
    "inquirer-9.2.23" = {
      name = "inquirer";
      packageName = "inquirer";
      version = "9.2.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/inquirer/-/inquirer-9.2.23.tgz";
        sha512 = "kod5s+FBPIDM2xiy9fu+6wdU/SkK5le5GS9lh4FEBjBHqiMgD9lLFbCbuqFNAjNL2ZOy9Wd9F694IOzN9pZHBA==";
      };
    };
    "inquirer-autocomplete-prompt-3.0.1" = {
      name = "inquirer-autocomplete-prompt";
      packageName = "inquirer-autocomplete-prompt";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/inquirer-autocomplete-prompt/-/inquirer-autocomplete-prompt-3.0.1.tgz";
        sha512 = "DQBXwX2fVQPVUzu4v4lGgtNgyjcX2+rTyphb2MeSOQh3xUayKAfHAF4y0KgsMi06m6ZiR3xIOdzMZMfQgX2m9w==";
      };
    };
    "ip-address-9.0.5" = {
      name = "ip-address";
      packageName = "ip-address";
      version = "9.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ip-address/-/ip-address-9.0.5.tgz";
        sha512 = "zHtQzGojZXTwZTHQqra+ETKd4Sn3vgi7uBmlPoXVWZqYvuKmtI0l/VZTjqGmJY9x88GGOaZ9+G9ES8hC4T4X8g==";
      };
    };
    "is-fullwidth-code-point-3.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
        sha512 = "zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
      };
    };
    "is-in-ci-0.1.0" = {
      name = "is-in-ci";
      packageName = "is-in-ci";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-in-ci/-/is-in-ci-0.1.0.tgz";
        sha512 = "d9PXLEY0v1iJ64xLiQMJ51J128EYHAaOR4yZqQi8aHGfw6KgifM3/Viw1oZZ1GCVmb3gBuyhLyHj0HgR2DhSXQ==";
      };
    };
    "is-installed-globally-0.4.0" = {
      name = "is-installed-globally";
      packageName = "is-installed-globally";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-installed-globally/-/is-installed-globally-0.4.0.tgz";
        sha512 = "iwGqO3J21aaSkC7jWnHP/difazwS7SFeIqxv6wEtLU8Y5KlzFTjyqcSIT0d8s4+dDhKytsk9PJZ2BkS5eZwQRQ==";
      };
    };
    "is-interactive-1.0.0" = {
      name = "is-interactive";
      packageName = "is-interactive";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-interactive/-/is-interactive-1.0.0.tgz";
        sha512 = "2HvIEKRoqS62guEC+qBjpvRubdX910WCMuJTZ+I9yvqKU2/12eSL549HMwtabb4oupdj2sMP50k+XJfB/8JE6w==";
      };
    };
    "is-interactive-2.0.0" = {
      name = "is-interactive";
      packageName = "is-interactive";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-interactive/-/is-interactive-2.0.0.tgz";
        sha512 = "qP1vozQRI+BMOPcjFzrjXuQvdak2pHNUMZoeG2eRbiSqyvbEf/wQtEOTOX1guk6E3t36RkaqiSt8A/6YElNxLQ==";
      };
    };
    "is-npm-6.0.0" = {
      name = "is-npm";
      packageName = "is-npm";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-npm/-/is-npm-6.0.0.tgz";
        sha512 = "JEjxbSmtPSt1c8XTkVrlujcXdKV1/tvuQ7GwKcAlyiVLeYFQ2VHat8xfrDJsIkhCdF/tZ7CiIR3sy141c6+gPQ==";
      };
    };
    "is-obj-2.0.0" = {
      name = "is-obj";
      packageName = "is-obj";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-obj/-/is-obj-2.0.0.tgz";
        sha512 = "drqDG3cbczxxEJRoOXcOjtdp1J/lyp1mNn0xaznRs8+muBhgQcrnbspox5X5fOw0HnMnbfDzvnEMEtqDEJEo8w==";
      };
    };
    "is-path-inside-3.0.3" = {
      name = "is-path-inside";
      packageName = "is-path-inside";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-path-inside/-/is-path-inside-3.0.3.tgz";
        sha512 = "Fd4gABb+ycGAmKou8eMftCupSir5lRxqf4aD/vd0cD2qc4HL07OjCeuHMr8Ro4CoMaeCKDB0/ECBOVWjTwUvPQ==";
      };
    };
    "is-stream-3.0.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-3.0.0.tgz";
        sha512 = "LnQR4bZ9IADDRSkvpqMGvt/tEJWclzklNgSw48V5EAaAeDd6qGvN8ei6k5p0tvxSR171VmGyHuTiAOfxAbr8kA==";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha512 = "cyA56iCMHAh5CdzjJIa4aohJyeO1YbwLi3Jc35MmRU6poroFjIGZzUzupGiRPOjgHg9TLu43xbpwXk523fMxKA==";
      };
    };
    "is-unicode-supported-0.1.0" = {
      name = "is-unicode-supported";
      packageName = "is-unicode-supported";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-unicode-supported/-/is-unicode-supported-0.1.0.tgz";
        sha512 = "knxG2q4UC3u8stRGyAVJCOdxFmv5DZiRcdlIaAQXAbSfJya+OhopNotLQrstBhququ4ZpuKbDc/8S6mgXgPFPw==";
      };
    };
    "is-unicode-supported-1.3.0" = {
      name = "is-unicode-supported";
      packageName = "is-unicode-supported";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-unicode-supported/-/is-unicode-supported-1.3.0.tgz";
        sha512 = "43r2mRvz+8JRIKnWJ+3j8JtjRKZ6GmjzfaE/qiBJnikNnYv/6bagRJ1kUhNk8R5EX/GkobD+r+sfxCPJsiKBLQ==";
      };
    };
    "is-unicode-supported-2.0.0" = {
      name = "is-unicode-supported";
      packageName = "is-unicode-supported";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-unicode-supported/-/is-unicode-supported-2.0.0.tgz";
        sha512 = "FRdAyx5lusK1iHG0TWpVtk9+1i+GjrzRffhDg4ovQ7mcidMQ6mj+MhKPmvh7Xwyv5gIS06ns49CA7Sqg7lC22Q==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha512 = "RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
      };
    };
    "jsbn-1.1.0" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-1.1.0.tgz";
        sha512 = "4bYVV3aAMtDTTu4+xsDYa6sy9GyJ69/amsu9sYF2zqjiEoZA5xJi3BrfX3uY+/IekIu7MwdObdbDWpoZdBv3/A==";
      };
    };
    "json-buffer-3.0.1" = {
      name = "json-buffer";
      packageName = "json-buffer";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-buffer/-/json-buffer-3.0.1.tgz";
        sha512 = "4bV5BfR2mqfQTJm+V5tPPdf+ZpuhiIvTuAB5g8kcrXOZpTT/QwwVRWBywX1ozr6lEuPdbHxwaJlm9G6mI2sfSQ==";
      };
    };
    "json-schema-traverse-1.0.0" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-1.0.0.tgz";
        sha512 = "NM8/P9n3XjXhIZn1lLhkFaACTOURQXjWhV4BA/RnOv8xvgqtqpAX9IO4mRQxSx1Rlo4tqzeqb0sOlruaOy3dug==";
      };
    };
    "json-schema-typed-8.0.1" = {
      name = "json-schema-typed";
      packageName = "json-schema-typed";
      version = "8.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-typed/-/json-schema-typed-8.0.1.tgz";
        sha512 = "XQmWYj2Sm4kn4WeTYvmpKEbyPsL7nBsb647c7pMe6l02/yx2+Jfc4dT6UZkEXnIUb5LhD55r2HPsJ1milQ4rDg==";
      };
    };
    "jsonfile-6.1.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-6.1.0.tgz";
        sha512 = "5dgndWOriYSm5cnYaJNhalLNDKOqFwyDB/rr1E9ZsGciGvKPs8R2xYGCacuf3z6K1YKDz182fd+fY3cn3pMqXQ==";
      };
    };
    "keyv-4.5.4" = {
      name = "keyv";
      packageName = "keyv";
      version = "4.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/keyv/-/keyv-4.5.4.tgz";
        sha512 = "oxVHkHR/EJf2CNXnWxRLW6mg7JyCCUcG0DtEGmL2ctUo1PNTin1PUil+r/+4r5MpVgC/fn1kjsx7mjSujKqIpw==";
      };
    };
    "latest-version-7.0.0" = {
      name = "latest-version";
      packageName = "latest-version";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/latest-version/-/latest-version-7.0.0.tgz";
        sha512 = "KvNT4XqAMzdcL6ka6Tl3i2lYeFDgXNCuIX+xNx6ZMVR1dFq+idXd9FLKNMOIx0t9mJ9/HudyX4oZWXZQ0UJHeg==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "log-symbols-4.1.0" = {
      name = "log-symbols";
      packageName = "log-symbols";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/log-symbols/-/log-symbols-4.1.0.tgz";
        sha512 = "8XPvpAA8uyhfteu8pIvQxpJZ7SYYdpUivZpGy6sFsBuKRY/7rQGavedeB8aK+Zkyq6upMFVL/9AW6vOYzfRyLg==";
      };
    };
    "log-symbols-6.0.0" = {
      name = "log-symbols";
      packageName = "log-symbols";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/log-symbols/-/log-symbols-6.0.0.tgz";
        sha512 = "i24m8rpwhmPIS4zscNzK6MSEhk0DUWa/8iYQWxhffV8jkI4Phvs3F+quL5xvS0gdQR0FyTCMMH33Y78dDTzzIw==";
      };
    };
    "lowercase-keys-3.0.0" = {
      name = "lowercase-keys";
      packageName = "lowercase-keys";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lowercase-keys/-/lowercase-keys-3.0.0.tgz";
        sha512 = "ozCC6gdQ+glXOQsveKD0YsDy8DSQFjDTz4zyzEHNV5+JP5D62LmfDZ6o1cycFx9ouG940M5dE8C8CTewdj2YWQ==";
      };
    };
    "lru-cache-7.18.3" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "7.18.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-7.18.3.tgz";
        sha512 = "jumlc0BIUrS3qJGgIkWZsyfAM7NCWiBcCDhnd+3NNM5KbBmLTgHVfWBcg6W+rLUsIpzpERPsvwUP7CckAQSOoA==";
      };
    };
    "meow-13.2.0" = {
      name = "meow";
      packageName = "meow";
      version = "13.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/meow/-/meow-13.2.0.tgz";
        sha512 = "pxQJQzB6djGPXh08dacEloMFopsOqGVRKFPYvPOt9XDZ1HasbgDZA74CJGreSU4G3Ak7EFJGoiH2auq+yXISgA==";
      };
    };
    "merge-stream-2.0.0" = {
      name = "merge-stream";
      packageName = "merge-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-stream/-/merge-stream-2.0.0.tgz";
        sha512 = "abv/qOcuPfk3URPfDzmZU1LKmuw8kT+0nIHvKrKgFrwifol/doWcdA4ZqsWQ8ENrFKkd67Mfpo/LovbIUsbt3w==";
      };
    };
    "mimic-fn-2.1.0" = {
      name = "mimic-fn";
      packageName = "mimic-fn";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-fn/-/mimic-fn-2.1.0.tgz";
        sha512 = "OqbOk5oEQeAZ8WXWydlu9HJjz9WVdEIvamMCcXmuqUYjTknH/sqsWvhQ3vgwKFRR1HpjvNBKQ37nbJgYzGqGcg==";
      };
    };
    "mimic-fn-4.0.0" = {
      name = "mimic-fn";
      packageName = "mimic-fn";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-fn/-/mimic-fn-4.0.0.tgz";
        sha512 = "vqiC06CuhBTUdZH+RYl8sFrL096vA45Ok5ISO6sE/Mr1jRbGH4Csnhi8f3wKVl7x8mO4Au7Ir9D3Oyv1VYMFJw==";
      };
    };
    "mimic-response-3.1.0" = {
      name = "mimic-response";
      packageName = "mimic-response";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-response/-/mimic-response-3.1.0.tgz";
        sha512 = "z0yWI+4FDrrweS8Zmt4Ej5HdJmky15+L2e6Wgn3+iK5fWzb6T3fhNFq2+MeTRb064c6Wr4N/wv0DzQTjNzHNGQ==";
      };
    };
    "mimic-response-4.0.0" = {
      name = "mimic-response";
      packageName = "mimic-response";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-response/-/mimic-response-4.0.0.tgz";
        sha512 = "e5ISH9xMYU0DzrT+jl8q2ze9D6eWBto+I8CNpe+VI+K2J/F/k3PdkdTdz4wvGVH4NTpo+NRYTVIuMQEMMcsLqg==";
      };
    };
    "minimist-1.2.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz";
        sha512 = "2yyAR8qBkN3YuheJanUpWC5U3bb5osDywNB8RzDVlDwDHbocAJveqqj1u8+SVD7jkWT4yvsHCpWqqWqAxb0zCA==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "mute-stream-1.0.0" = {
      name = "mute-stream";
      packageName = "mute-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mute-stream/-/mute-stream-1.0.0.tgz";
        sha512 = "avsJQhyd+680gKXyG/sQc0nXaC6rBkPOfyHYcFb9+hdkqQkR9bdnkJ0AMZhke0oesPqIO+mFFJ+IdBc7mst4IA==";
      };
    };
    "netmask-2.0.2" = {
      name = "netmask";
      packageName = "netmask";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/netmask/-/netmask-2.0.2.tgz";
        sha512 = "dBpDMdxv9Irdq66304OLfEmQ9tbNRFnFTuZiLo+bD+r332bBmMJ8GBLXklIXXgxd3+v9+KUnZaUR5PJMa75Gsg==";
      };
    };
    "node-domexception-1.0.0" = {
      name = "node-domexception";
      packageName = "node-domexception";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-domexception/-/node-domexception-1.0.0.tgz";
        sha512 = "/jKZoMpw0F8GRwl4/eLROPA3cfcXtLApP0QzLmUT/HuPCZWyB7IY9ZrMeKw2O/nFIqPQB3PVM9aYm0F312AXDQ==";
      };
    };
    "node-fetch-3.3.2" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-3.3.2.tgz";
        sha512 = "dRB78srN/l6gqWulah9SrxeYnxeddIG30+GOqK/9OlLVyLg3HPnr6SqOWTWOXKRwC2eGYCkZ59NNuSgvSrpgOA==";
      };
    };
    "normalize-url-8.0.1" = {
      name = "normalize-url";
      packageName = "normalize-url";
      version = "8.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-url/-/normalize-url-8.0.1.tgz";
        sha512 = "IO9QvjUMWxPQQhs60oOu10CRkWCiZzSUkzbXGGV9pviYl1fXYcvkzQ5jV9z8Y6un8ARoVRl4EtC6v6jNqbaJ/w==";
      };
    };
    "npm-run-path-5.3.0" = {
      name = "npm-run-path";
      packageName = "npm-run-path";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-run-path/-/npm-run-path-5.3.0.tgz";
        sha512 = "ppwTtiJZq0O/ai0z7yfudtBpWIoxM8yE6nHi1X47eFR2EWORqfbu6CnPlNsjeN683eT0qG6H/Pyf9fCcvjnnnQ==";
      };
    };
    "onetime-5.1.2" = {
      name = "onetime";
      packageName = "onetime";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/onetime/-/onetime-5.1.2.tgz";
        sha512 = "kbpaSSGJTWdAY5KPVeMOKXSrPtr8C8C7wodJbcsd51jRnmD+GZu8Y0VoU6Dm5Z4vWr0Ig/1NKuWRKf7j5aaYSg==";
      };
    };
    "onetime-6.0.0" = {
      name = "onetime";
      packageName = "onetime";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/onetime/-/onetime-6.0.0.tgz";
        sha512 = "1FlR+gjXK7X+AsAHso35MnyN5KqGwJRi/31ft6x0M194ht7S+rWAvd7PHss9xSKMzE0asv1pyIHaJYq+BbacAQ==";
      };
    };
    "ora-5.4.1" = {
      name = "ora";
      packageName = "ora";
      version = "5.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ora/-/ora-5.4.1.tgz";
        sha512 = "5b6Y85tPxZZ7QytO+BQzysW31HJku27cRIlkbAXaNx+BdcVi+LlRFmVXzeF6a7JCwJpyw5c4b+YSVImQIrBpuQ==";
      };
    };
    "ora-8.0.1" = {
      name = "ora";
      packageName = "ora";
      version = "8.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ora/-/ora-8.0.1.tgz";
        sha512 = "ANIvzobt1rls2BDny5fWZ3ZVKyD6nscLvfFRpQgfWsythlcsVUC9kL0zq6j2Z5z9wwp1kd7wpsD/T9qNPVLCaQ==";
      };
    };
    "os-tmpdir-1.0.2" = {
      name = "os-tmpdir";
      packageName = "os-tmpdir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-tmpdir/-/os-tmpdir-1.0.2.tgz";
        sha512 = "D2FR03Vir7FIu45XBY20mTb+/ZSWB00sjU9jdQXt83gDrI4Ztz5Fs7/yy74g2N5SVQY4xY1qDr4rNddwYRVX0g==";
      };
    };
    "p-cancelable-3.0.0" = {
      name = "p-cancelable";
      packageName = "p-cancelable";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-cancelable/-/p-cancelable-3.0.0.tgz";
        sha512 = "mlVgR3PGuzlo0MmTdk4cXqXWlwQDLnONTAg6sm62XkMJEiRxN3GL3SffkYvqwonbkJBcrI7Uvv5Zh9yjvn2iUw==";
      };
    };
    "pac-proxy-agent-7.0.2" = {
      name = "pac-proxy-agent";
      packageName = "pac-proxy-agent";
      version = "7.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pac-proxy-agent/-/pac-proxy-agent-7.0.2.tgz";
        sha512 = "BFi3vZnO9X5Qt6NRz7ZOaPja3ic0PhlsmCRYLOpN11+mWBCR6XJDqW5RF3j8jm4WGGQZtBA+bTfxYzeKW73eHg==";
      };
    };
    "pac-resolver-7.0.1" = {
      name = "pac-resolver";
      packageName = "pac-resolver";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pac-resolver/-/pac-resolver-7.0.1.tgz";
        sha512 = "5NPgf87AT2STgwa2ntRMr45jTKrYBGkVU36yT0ig/n/GMAa3oPqhZfIQ2kMEimReg0+t9kZViDVZ83qfVUlckg==";
      };
    };
    "package-json-8.1.1" = {
      name = "package-json";
      packageName = "package-json";
      version = "8.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/package-json/-/package-json-8.1.1.tgz";
        sha512 = "cbH9IAIJHNj9uXi196JVsRlt7cHKak6u/e6AkL/bkRelZ7rlL3X1YKxsZwa36xipOEKAsdtmaG6aAJoM1fx2zA==";
      };
    };
    "path-exists-5.0.0" = {
      name = "path-exists";
      packageName = "path-exists";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-exists/-/path-exists-5.0.0.tgz";
        sha512 = "RjhtfwJOxzcFmNOi6ltcbcu4Iu+FL3zEj83dk4kAS+fVpTxXLO1b38RvJgT/0QwvV/L3aY9TAnyv0EOqW4GoMQ==";
      };
    };
    "path-key-3.1.1" = {
      name = "path-key";
      packageName = "path-key";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
        sha512 = "ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
      };
    };
    "path-key-4.0.0" = {
      name = "path-key";
      packageName = "path-key";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-4.0.0.tgz";
        sha512 = "haREypq7xkM7ErfgIyA0z+Bj4AGKlMSdlQE2jvJo6huWD1EdkKYV+G/T4nq0YEF2vgTT8kqMFKo1uHn950r4SQ==";
      };
    };
    "picocolors-1.0.1" = {
      name = "picocolors";
      packageName = "picocolors";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picocolors/-/picocolors-1.0.1.tgz";
        sha512 = "anP1Z8qwhkbmu7MFP5iTt+wQKXgwzf7zTyGlcdzabySa9vd0Xt392U0rVmz9poOaBj0uHJKyyo9/upk0HrEQew==";
      };
    };
    "proto-list-1.2.4" = {
      name = "proto-list";
      packageName = "proto-list";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/proto-list/-/proto-list-1.2.4.tgz";
        sha512 = "vtK/94akxsTMhe0/cbfpR+syPuszcuwhqVjJq26CuNDgFGj682oRBXOP5MJpv2r7JtE8MsiepGIqvvOTBwn2vA==";
      };
    };
    "proxy-agent-6.4.0" = {
      name = "proxy-agent";
      packageName = "proxy-agent";
      version = "6.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-agent/-/proxy-agent-6.4.0.tgz";
        sha512 = "u0piLU+nCOHMgGjRbimiXmA9kM/L9EHh3zL81xCdp7m+Y2pHIsnmbdDoEDoAz5geaonNR6q6+yOPQs6n4T6sBQ==";
      };
    };
    "proxy-from-env-1.1.0" = {
      name = "proxy-from-env";
      packageName = "proxy-from-env";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-from-env/-/proxy-from-env-1.1.0.tgz";
        sha512 = "D+zkORCbA9f1tdWRK0RaCR3GPv50cMxcrz4X8k5LTSUD1Dkw47mKJEZQNunItRTkWwgtaUSo1RVFRIG9ZXiFYg==";
      };
    };
    "punycode-2.3.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-2.3.1.tgz";
        sha512 = "vYt7UD1U9Wg6138shLtLOvdAu+8DsC/ilFtEVHcH+wydcSpNE20AfSOduf6MkRFahL5FY7X1oU7nKVZFtfq8Fg==";
      };
    };
    "pupa-3.1.0" = {
      name = "pupa";
      packageName = "pupa";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pupa/-/pupa-3.1.0.tgz";
        sha512 = "FLpr4flz5xZTSJxSeaheeMKN/EDzMdK7b8PTOC6a5PYFKTucWbdqjgqaEyH0shFiSJrVB1+Qqi4Tk19ccU6Aug==";
      };
    };
    "quick-lru-5.1.1" = {
      name = "quick-lru";
      packageName = "quick-lru";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/quick-lru/-/quick-lru-5.1.1.tgz";
        sha512 = "WuyALRjWPDGtt/wzJiadO5AXY+8hZ80hVpe6MyivgraREW751X3SbhRvG3eLKOYN+8VEvqLcf3wdnt44Z4S4SA==";
      };
    };
    "rc-1.2.8" = {
      name = "rc";
      packageName = "rc";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/rc/-/rc-1.2.8.tgz";
        sha512 = "y3bGgqKj3QBdxLbLkomlohkvsA8gdAiUQlSBJnBhfn+BPxg4bc62d8TcBW15wavDfgexCgccckhcZvywyQYPOw==";
      };
    };
    "readable-stream-3.6.2" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.2.tgz";
        sha512 = "9u/sniCrY3D5WdsERHzHE4G2YCXqoG5FTHUiCC4SIbr6XcLZBY05ya9EKjYek9O5xOAwjGq+1JdGBAS7Q9ScoA==";
      };
    };
    "registry-auth-token-5.0.2" = {
      name = "registry-auth-token";
      packageName = "registry-auth-token";
      version = "5.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/registry-auth-token/-/registry-auth-token-5.0.2.tgz";
        sha512 = "o/3ikDxtXaA59BmZuZrJZDJv8NMDGSj+6j6XaeBmHw8eY1i1qd9+6H+LjVvQXx3HN6aRCGa1cUdJ9RaJZUugnQ==";
      };
    };
    "registry-url-6.0.1" = {
      name = "registry-url";
      packageName = "registry-url";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/registry-url/-/registry-url-6.0.1.tgz";
        sha512 = "+crtS5QjFRqFCoQmvGduwYWEBng99ZvmFvF+cUJkGYF1L1BfU8C6Zp9T7f5vPAwyLkUExpvK+ANVZmGU49qi4Q==";
      };
    };
    "require-from-string-2.0.2" = {
      name = "require-from-string";
      packageName = "require-from-string";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-from-string/-/require-from-string-2.0.2.tgz";
        sha512 = "Xf0nWe6RseziFMu+Ap9biiUbmplq6S9/p+7w7YXP/JBHhrUDDUhwa+vANyubuqfZWTveU//DYVGsDG7RKL/vEw==";
      };
    };
    "resolve-alpn-1.2.1" = {
      name = "resolve-alpn";
      packageName = "resolve-alpn";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-alpn/-/resolve-alpn-1.2.1.tgz";
        sha512 = "0a1F4l73/ZFZOakJnQ3FvkJ2+gSTQWz/r2KE5OdDY0TxPm5h4GkqkWWfM47T7HsbnOtcJVEF4epCVy6u7Q3K+g==";
      };
    };
    "responselike-3.0.0" = {
      name = "responselike";
      packageName = "responselike";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/responselike/-/responselike-3.0.0.tgz";
        sha512 = "40yHxbNcl2+rzXvZuVkrYohathsSJlMTXKryG5y8uciHv1+xDLHQpgjG64JUO9nrEq2jGLH6IZ8BcZyw3wrweg==";
      };
    };
    "restore-cursor-3.1.0" = {
      name = "restore-cursor";
      packageName = "restore-cursor";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/restore-cursor/-/restore-cursor-3.1.0.tgz";
        sha512 = "l+sSefzHpj5qimhFSE5a8nufZYAM3sBSVMAPtYkmC+4EH2anSGaEMXSD0izRQbu9nfyQ9y5JrVmp7E8oZrUjvA==";
      };
    };
    "restore-cursor-4.0.0" = {
      name = "restore-cursor";
      packageName = "restore-cursor";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/restore-cursor/-/restore-cursor-4.0.0.tgz";
        sha512 = "I9fPXU9geO9bHOt9pHHOhOkYerIMsmVaWB0rA2AI9ERh/+x/i7MV5HKBNrg+ljO5eoPVgCcnFuRjJ9uH6I/3eg==";
      };
    };
    "run-async-2.4.1" = {
      name = "run-async";
      packageName = "run-async";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-async/-/run-async-2.4.1.tgz";
        sha512 = "tvVnVv01b8c1RrA6Ep7JkStj85Guv/YrMcwqYQnwjsAS2cTmmPGBBjAjpCW7RrSodNSoE2/qg9O4bceNvUuDgQ==";
      };
    };
    "run-async-3.0.0" = {
      name = "run-async";
      packageName = "run-async";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-async/-/run-async-3.0.0.tgz";
        sha512 = "540WwVDOMxA6dN6We19EcT9sc3hkXPw5mzRNGM3FkdN/vtE9NFvj5lFAPNwUDmJjXidm3v7TC1cTE7t17Ulm1Q==";
      };
    };
    "rxjs-7.8.1" = {
      name = "rxjs";
      packageName = "rxjs";
      version = "7.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rxjs/-/rxjs-7.8.1.tgz";
        sha512 = "AA3TVj+0A2iuIoQkWEK/tqFjBq2j+6PO6Y0zJcvzLAFhEFIO3HL0vls9hWLncZbAAbK0mar7oZ4V079I/qPMxg==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "semver-7.6.2" = {
      name = "semver";
      packageName = "semver";
      version = "7.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.6.2.tgz";
        sha512 = "FNAIBWCx9qcRhoHcgcJ0gvU7SN1lYU2ZXuSfl04bSC5OpvDHFyJCjdNHomPXxjQlCBU67YW64PzY7/VIEH7F2w==";
      };
    };
    "semver-diff-4.0.0" = {
      name = "semver-diff";
      packageName = "semver-diff";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver-diff/-/semver-diff-4.0.0.tgz";
        sha512 = "0Ju4+6A8iOnpL/Thra7dZsSlOHYAHIeMxfhWQRI1/VLcT3WDBZKKtQt/QkBOsiIN9ZpuvHE6cGZ0x4glCMmfiA==";
      };
    };
    "set-function-length-1.2.2" = {
      name = "set-function-length";
      packageName = "set-function-length";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-function-length/-/set-function-length-1.2.2.tgz";
        sha512 = "pgRc4hJ4/sNjWCSS9AmnS40x3bNMDTknHgL5UaMBTMyJnU90EgWh1Rz+MC9eFu4BuN/UwZjKQuY/1v3rM7HMfg==";
      };
    };
    "shebang-command-2.0.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
        sha512 = "kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
      };
    };
    "shebang-regex-3.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
        sha512 = "7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
      };
    };
    "signal-exit-3.0.7" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.7.tgz";
        sha512 = "wnD2ZE+l+SPC/uoS0vXeE9L1+0wuaMqKlfz9AMUo38JsyLSBWSFcHR1Rri62LZc12vLr1gb3jl7iwQhgwpAbGQ==";
      };
    };
    "signal-exit-4.1.0" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-4.1.0.tgz";
        sha512 = "bzyZ1e88w9O1iNJbKnOlvYTrWPDl46O1bG0D3XInv+9tkPrxrN8jUUTiFlDkkmKWgn1M6CfIA13SuGqOa9Korw==";
      };
    };
    "smart-buffer-4.2.0" = {
      name = "smart-buffer";
      packageName = "smart-buffer";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/smart-buffer/-/smart-buffer-4.2.0.tgz";
        sha512 = "94hK0Hh8rPqQl2xXc3HsaBoOXKV20MToPkcXvwbISWLEs+64sBq5kFgn2kJDHb1Pry9yrP0dxrCI9RRci7RXKg==";
      };
    };
    "socks-2.8.3" = {
      name = "socks";
      packageName = "socks";
      version = "2.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/socks/-/socks-2.8.3.tgz";
        sha512 = "l5x7VUUWbjVFbafGLxPWkYsHIhEvmF85tbIeFZWc8ZPtoMyybuEhL7Jye/ooC4/d48FgOjSJXgsF/AJPYCW8Zw==";
      };
    };
    "socks-proxy-agent-8.0.4" = {
      name = "socks-proxy-agent";
      packageName = "socks-proxy-agent";
      version = "8.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/socks-proxy-agent/-/socks-proxy-agent-8.0.4.tgz";
        sha512 = "GNAq/eg8Udq2x0eNiFkr9gRg5bA7PXEWagQdeRX4cPSG+X/8V38v637gim9bjFptMk1QWsCTr0ttrJEiXbNnRw==";
      };
    };
    "sprintf-js-1.1.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.1.3.tgz";
        sha512 = "Oo+0REFV59/rz3gfJNKQiBlwfHaSESl1pcGyABQsnnIfWOFt6JNj5gCog2U6MLZ//IGYD+nA8nI+mTShREReaA==";
      };
    };
    "stdin-discarder-0.2.2" = {
      name = "stdin-discarder";
      packageName = "stdin-discarder";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/stdin-discarder/-/stdin-discarder-0.2.2.tgz";
        sha512 = "UhDfHmA92YAlNnCfhmq0VeNL5bDbiZGg7sZ2IvPsXubGkiNa9EC+tUTsjBRsYUAz87btI6/1wf4XoVvQ3uRnmQ==";
      };
    };
    "string-width-4.2.3" = {
      name = "string-width";
      packageName = "string-width";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
        sha512 = "wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      };
    };
    "string-width-5.1.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-5.1.2.tgz";
        sha512 = "HnLOCR3vjcY8beoNLtcjZ5/nxn2afmME6lhrDrebokqMap+XbeW8n9TXpPDOqdGK5qcI3oT0GKTW6wC7EMiVqA==";
      };
    };
    "string-width-7.2.0" = {
      name = "string-width";
      packageName = "string-width";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-7.2.0.tgz";
        sha512 = "tsaTIkKW9b4N+AEj+SVA+WhJzV7/zMhcSu78mLKWSk7cXMOSHsBKFWUs0fWwq8QyK3MgJBQRX6Gbi4kYbdvGkQ==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "strip-ansi-6.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "strip-ansi-7.1.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-7.1.0.tgz";
        sha512 = "iq6eVVI64nQQTRYq2KtEg2d2uU7LElhTJwsH4YzIHZshxlgZms/wIc4VoDQTlG/IvVIrBKG06CrZnp0qv7hkcQ==";
      };
    };
    "strip-final-newline-3.0.0" = {
      name = "strip-final-newline";
      packageName = "strip-final-newline";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-final-newline/-/strip-final-newline-3.0.0.tgz";
        sha512 = "dOESqjYr96iWYylGObzd39EuNTa5VJxyvVAEm5Jnh7KGo75V43Hk1odPQkNDyXNmUR6k+gEiDVXnjB8HJ3crXw==";
      };
    };
    "strip-json-comments-2.0.1" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-2.0.1.tgz";
        sha512 = "4gB8na07fecVVkOI6Rs4e7T6NOTki5EmL7TUduTs6bu3EdnSycntVJ4re8kgZA+wx9IueI2Y11bfbgwtzuE0KQ==";
      };
    };
    "stubborn-fs-1.2.5" = {
      name = "stubborn-fs";
      packageName = "stubborn-fs";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/stubborn-fs/-/stubborn-fs-1.2.5.tgz";
        sha512 = "H2N9c26eXjzL/S/K+i/RHHcFanE74dptvvjM8iwzwbVcWY/zjBbgRqF3K0DY4+OD+uTTASTBvDoxPDaPN02D7g==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "tmp-0.0.33" = {
      name = "tmp";
      packageName = "tmp";
      version = "0.0.33";
      src = fetchurl {
        url = "https://registry.npmjs.org/tmp/-/tmp-0.0.33.tgz";
        sha512 = "jRCJlojKnZ3addtTOjdIqoRuPEKBvNXcGYqzO6zWZX8KfKEpnGY5jfggJQ3EjKuu8D4bJRr0y+cYJFmYbImXGw==";
      };
    };
    "tslib-2.6.3" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.6.3.tgz";
        sha512 = "xNvxJEOUiWPGhUuUdQgAJPKOOJfGnIyKySOc09XkKsgdUV/3E2zvwZYdejjmRgPCgcym1juLH3226yA7sEFJKQ==";
      };
    };
    "type-fest-0.21.3" = {
      name = "type-fest";
      packageName = "type-fest";
      version = "0.21.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-fest/-/type-fest-0.21.3.tgz";
        sha512 = "t0rzBq87m3fVcduHDUFhKmyyX+9eo6WQjZvf51Ea/M0Q7+T374Jp1aUiyUl0GKxp8M/OETVHSDvmkyPgvX+X2w==";
      };
    };
    "type-fest-1.4.0" = {
      name = "type-fest";
      packageName = "type-fest";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-fest/-/type-fest-1.4.0.tgz";
        sha512 = "yGSza74xk0UG8k+pLh5oeoYirvIiWo5t0/o3zHHAO2tRDiZcxWP7fywNlXhqb6/r6sWvwi+RsyQMWhVLe4BVuA==";
      };
    };
    "type-fest-2.19.0" = {
      name = "type-fest";
      packageName = "type-fest";
      version = "2.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-fest/-/type-fest-2.19.0.tgz";
        sha512 = "RAH822pAdBgcNMAfWnCBU3CFZcfZ/i1eZjwFU/dsLKumyuuP3niueg2UAukXYF0E2AAoc82ZSSf9J0WQBinzHA==";
      };
    };
    "type-fest-3.13.1" = {
      name = "type-fest";
      packageName = "type-fest";
      version = "3.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-fest/-/type-fest-3.13.1.tgz";
        sha512 = "tLq3bSNx+xSpwvAJnzrK0Ep5CLNWjvFTOp71URMaAEWBfRb9nnJiBoUe0tF8bI4ZFO3omgBR6NvnbzVUT3Ly4g==";
      };
    };
    "typedarray-to-buffer-3.1.5" = {
      name = "typedarray-to-buffer";
      packageName = "typedarray-to-buffer";
      version = "3.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray-to-buffer/-/typedarray-to-buffer-3.1.5.tgz";
        sha512 = "zdu8XMNEDepKKR+XYOXAVPtWui0ly0NtohUscw+UmaHiAWT8hrV1rr//H6V+0DvJ3OQ19S979M0laLfX8rm82Q==";
      };
    };
    "uint8array-extras-0.3.0" = {
      name = "uint8array-extras";
      packageName = "uint8array-extras";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uint8array-extras/-/uint8array-extras-0.3.0.tgz";
        sha512 = "erJsJwQ0tKdwuqI0359U8ijkFmfiTcq25JvvzRVc1VP+2son1NJRXhxcAKJmAW3ajM8JSGAfsAXye8g4s+znxA==";
      };
    };
    "unique-string-3.0.0" = {
      name = "unique-string";
      packageName = "unique-string";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unique-string/-/unique-string-3.0.0.tgz";
        sha512 = "VGXBUVwxKMBUznyffQweQABPRRW1vHZAbadFZud4pLFAqRGvv/96vafgjWFqzourzr8YonlQiPgH0YCJfawoGQ==";
      };
    };
    "universalify-2.0.1" = {
      name = "universalify";
      packageName = "universalify";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/universalify/-/universalify-2.0.1.tgz";
        sha512 = "gptHNQghINnc/vTGIk0SOFGFNXw7JVrlRUtConJRlvaw6DuX0wO5Jeko9sWrMBhh+PsYAZ7oXAiOnf/UKogyiw==";
      };
    };
    "update-notifier-7.0.0" = {
      name = "update-notifier";
      packageName = "update-notifier";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/update-notifier/-/update-notifier-7.0.0.tgz";
        sha512 = "Hv25Bh+eAbOLlsjJreVPOs4vd51rrtCrmhyOJtbpAojro34jS4KQaEp4/EvlHJX7jSO42VvEFpkastVyXyIsdQ==";
      };
    };
    "uri-js-4.4.1" = {
      name = "uri-js";
      packageName = "uri-js";
      version = "4.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uri-js/-/uri-js-4.4.1.tgz";
        sha512 = "7rKUyy33Q1yc98pQ1DAmLtwX109F7TIfWlW1Ydo8Wl1ii1SeHieeh0HHfPeL2fMXK6z0s8ecKs9frCuLJvndBg==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha512 = "EPD5q1uXyFxJpCrLnCc1nHnq3gOa6DZBocAIiI2TaSCA7VCJ1UJDMagCzIkXNsUYfD1daK//LTEQ8xiIbrHtcw==";
      };
    };
    "validator-13.12.0" = {
      name = "validator";
      packageName = "validator";
      version = "13.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/validator/-/validator-13.12.0.tgz";
        sha512 = "c1Q0mCiPlgdTVVVIJIrBuxNicYE+t/7oKeI9MWLj3fh/uq2Pxh/3eeWbVZ4OcGW1TUf53At0njHw5SMdA3tmMg==";
      };
    };
    "wcwidth-1.0.1" = {
      name = "wcwidth";
      packageName = "wcwidth";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/wcwidth/-/wcwidth-1.0.1.tgz";
        sha512 = "XHPEwS0q6TaxcvG85+8EYkbiCux2XtWG2mkc47Ng2A77BQu9+DqIOJldST4HgPkuea7dvKSj5VgX3P1d4rW8Tg==";
      };
    };
    "web-streams-polyfill-3.3.3" = {
      name = "web-streams-polyfill";
      packageName = "web-streams-polyfill";
      version = "3.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/web-streams-polyfill/-/web-streams-polyfill-3.3.3.tgz";
        sha512 = "d2JWLCivmZYTSIoge9MsgFCZrt571BikcWGYkjC1khllbTeDlGqZ2D8vD8E/lJa8WGWbb7Plm8/XJYV7IJHZZw==";
      };
    };
    "when-exit-2.1.3" = {
      name = "when-exit";
      packageName = "when-exit";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/when-exit/-/when-exit-2.1.3.tgz";
        sha512 = "uVieSTccFIr/SFQdFWN/fFaQYmV37OKtuaGphMAzi4DmmUlrvRBJW5WSLkHyjNQY/ePJMz3LoiX9R3yy1Su6Hw==";
      };
    };
    "which-2.0.2" = {
      name = "which";
      packageName = "which";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
        sha512 = "BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      };
    };
    "widest-line-4.0.1" = {
      name = "widest-line";
      packageName = "widest-line";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/widest-line/-/widest-line-4.0.1.tgz";
        sha512 = "o0cyEG0e8GPzT4iGHphIOh0cJOV8fivsXxddQasHPHfoZf1ZexrfeA21w2NaEN1RHE+fXlfISmOE8R9N3u3Qig==";
      };
    };
    "wrap-ansi-6.2.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "6.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-6.2.0.tgz";
        sha512 = "r6lPcBGxZXlIcymEu7InxDMhdW0KDxpLgoFLcguasxCaJ/SOIZwINatK9KY/tf+ZrlywOKU0UDj3ATXUBfxJXA==";
      };
    };
    "wrap-ansi-8.1.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-8.1.0.tgz";
        sha512 = "si7QWI6zUMq56bESFvagtmzMdGOtoxfR+Sez11Mobfc7tm+VkUckk9bW2UeffTGVUbOksxmSw0AA2gs8g71NCQ==";
      };
    };
    "write-file-atomic-3.0.3" = {
      name = "write-file-atomic";
      packageName = "write-file-atomic";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/write-file-atomic/-/write-file-atomic-3.0.3.tgz";
        sha512 = "AvHcyZ5JnSfq3ioSyjrBkH9yW4m7Ayk8/9My/DD9onKeu/94fwrMocemO2QAJFAlnnDN+ZDS+ZjAR5ua1/PV/Q==";
      };
    };
    "xdg-basedir-5.1.0" = {
      name = "xdg-basedir";
      packageName = "xdg-basedir";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xdg-basedir/-/xdg-basedir-5.1.0.tgz";
        sha512 = "GCPAHLvrIH13+c0SuacwvRYj2SxJXQ4kaVTT5xgL3kPrz56XxkF21IGhjSE1+W0aw7gpBWRGXLCPnPby6lSpmQ==";
      };
    };
  };
  args = {
    name = "gitmoji-cli";
    packageName = "gitmoji-cli";
    src = ./.;
    dependencies = [
      sources."@inquirer/figures-1.0.3"
      sources."@ljharb/through-2.3.13"
      sources."@pnpm/config.env-replace-1.1.0"
      (sources."@pnpm/network.ca-file-1.0.2" // {
        dependencies = [
          sources."graceful-fs-4.2.10"
        ];
      })
      sources."@pnpm/npm-conf-2.2.2"
      sources."@sindresorhus/is-5.6.0"
      sources."@szmarczak/http-timer-5.0.1"
      sources."@tootallnate/quickjs-emscripten-0.23.0"
      sources."@types/http-cache-semantics-4.0.4"
      sources."agent-base-7.1.1"
      sources."ajv-8.16.0"
      sources."ajv-formats-2.1.1"
      sources."ansi-align-3.0.1"
      (sources."ansi-escapes-4.3.2" // {
        dependencies = [
          sources."type-fest-0.21.3"
        ];
      })
      sources."ansi-regex-5.0.1"
      sources."ansi-styles-4.3.0"
      sources."ast-types-0.13.4"
      sources."atomically-2.0.3"
      sources."base64-js-1.5.1"
      sources."basic-ftp-5.0.5"
      sources."bl-4.1.0"
      (sources."boxen-7.1.1" // {
        dependencies = [
          sources."ansi-regex-6.0.1"
          sources."ansi-styles-6.2.1"
          sources."emoji-regex-9.2.2"
          sources."string-width-5.1.2"
          sources."strip-ansi-7.1.0"
          sources."type-fest-2.19.0"
          sources."wrap-ansi-8.1.0"
        ];
      })
      sources."buffer-5.7.1"
      sources."cacheable-lookup-7.0.0"
      (sources."cacheable-request-10.2.14" // {
        dependencies = [
          sources."get-stream-6.0.1"
        ];
      })
      sources."call-bind-1.0.7"
      sources."camelcase-7.0.1"
      sources."chalk-5.3.0"
      sources."chardet-0.7.0"
      sources."cli-boxes-3.0.0"
      sources."cli-cursor-3.1.0"
      sources."cli-spinners-2.9.2"
      sources."cli-width-4.1.0"
      sources."clone-1.0.4"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."conf-12.0.0"
      (sources."config-chain-1.1.13" // {
        dependencies = [
          sources."ini-1.3.8"
        ];
      })
      (sources."configstore-6.0.0" // {
        dependencies = [
          sources."dot-prop-6.0.1"
        ];
      })
      sources."cross-spawn-7.0.3"
      (sources."crypto-random-string-4.0.0" // {
        dependencies = [
          sources."type-fest-1.4.0"
        ];
      })
      sources."data-uri-to-buffer-4.0.1"
      sources."debounce-fn-5.1.2"
      sources."debug-4.3.5"
      (sources."decompress-response-6.0.0" // {
        dependencies = [
          sources."mimic-response-3.1.0"
        ];
      })
      sources."deep-extend-0.6.0"
      sources."defaults-1.0.4"
      sources."defer-to-connect-2.0.1"
      sources."define-data-property-1.1.4"
      sources."degenerator-5.0.1"
      sources."dot-prop-8.0.2"
      sources."eastasianwidth-0.2.0"
      sources."emoji-regex-8.0.0"
      sources."env-paths-3.0.0"
      sources."es-define-property-1.0.0"
      sources."es-errors-1.3.0"
      sources."escape-goat-4.0.0"
      sources."escape-string-regexp-5.0.0"
      sources."escodegen-2.1.0"
      sources."esprima-4.0.1"
      sources."estraverse-5.3.0"
      sources."esutils-2.0.3"
      sources."execa-8.0.1"
      sources."external-editor-3.1.0"
      sources."fast-deep-equal-3.1.3"
      sources."fetch-blob-3.2.0"
      (sources."figures-5.0.0" // {
        dependencies = [
          sources."is-unicode-supported-1.3.0"
        ];
      })
      sources."form-data-encoder-2.1.4"
      sources."formdata-polyfill-4.0.10"
      sources."fs-extra-11.2.0"
      sources."function-bind-1.1.2"
      sources."fuse.js-7.0.0"
      sources."get-east-asian-width-1.2.0"
      sources."get-intrinsic-1.2.4"
      sources."get-stream-8.0.1"
      (sources."get-uri-6.0.3" // {
        dependencies = [
          sources."data-uri-to-buffer-6.0.2"
        ];
      })
      sources."gitmoji-cli-9.4.0"
      sources."global-dirs-3.0.1"
      sources."gopd-1.0.1"
      (sources."got-12.6.1" // {
        dependencies = [
          sources."get-stream-6.0.1"
        ];
      })
      sources."graceful-fs-4.2.11"
      sources."has-flag-4.0.0"
      sources."has-property-descriptors-1.0.2"
      sources."has-proto-1.0.3"
      sources."has-symbols-1.0.3"
      sources."hasown-2.0.2"
      sources."http-cache-semantics-4.1.1"
      sources."http-proxy-agent-7.0.2"
      sources."http2-wrapper-2.2.1"
      sources."https-proxy-agent-7.0.5"
      sources."human-signals-5.0.0"
      sources."iconv-lite-0.4.24"
      sources."ieee754-1.2.1"
      sources."import-lazy-4.0.0"
      sources."imurmurhash-0.1.4"
      sources."inherits-2.0.4"
      sources."ini-2.0.0"
      (sources."inquirer-9.2.23" // {
        dependencies = [
          (sources."ora-5.4.1" // {
            dependencies = [
              sources."chalk-4.1.2"
            ];
          })
        ];
      })
      (sources."inquirer-autocomplete-prompt-3.0.1" // {
        dependencies = [
          sources."ansi-escapes-6.2.1"
          sources."run-async-2.4.1"
        ];
      })
      sources."ip-address-9.0.5"
      sources."is-fullwidth-code-point-3.0.0"
      sources."is-in-ci-0.1.0"
      sources."is-installed-globally-0.4.0"
      sources."is-interactive-1.0.0"
      sources."is-npm-6.0.0"
      sources."is-obj-2.0.0"
      sources."is-path-inside-3.0.3"
      sources."is-stream-3.0.0"
      sources."is-typedarray-1.0.0"
      sources."is-unicode-supported-0.1.0"
      sources."isexe-2.0.0"
      sources."jsbn-1.1.0"
      sources."json-buffer-3.0.1"
      sources."json-schema-traverse-1.0.0"
      sources."json-schema-typed-8.0.1"
      sources."jsonfile-6.1.0"
      sources."keyv-4.5.4"
      sources."latest-version-7.0.0"
      sources."lodash-4.17.21"
      (sources."log-symbols-4.1.0" // {
        dependencies = [
          sources."chalk-4.1.2"
        ];
      })
      sources."lowercase-keys-3.0.0"
      sources."lru-cache-7.18.3"
      sources."meow-13.2.0"
      sources."merge-stream-2.0.0"
      sources."mimic-fn-4.0.0"
      sources."mimic-response-4.0.0"
      sources."minimist-1.2.8"
      sources."ms-2.1.2"
      sources."mute-stream-1.0.0"
      sources."netmask-2.0.2"
      sources."node-domexception-1.0.0"
      sources."node-fetch-3.3.2"
      sources."normalize-url-8.0.1"
      (sources."npm-run-path-5.3.0" // {
        dependencies = [
          sources."path-key-4.0.0"
        ];
      })
      sources."onetime-6.0.0"
      (sources."ora-8.0.1" // {
        dependencies = [
          sources."ansi-regex-6.0.1"
          sources."cli-cursor-4.0.0"
          sources."emoji-regex-10.3.0"
          sources."is-interactive-2.0.0"
          sources."is-unicode-supported-2.0.0"
          (sources."log-symbols-6.0.0" // {
            dependencies = [
              sources."is-unicode-supported-1.3.0"
            ];
          })
          sources."mimic-fn-2.1.0"
          sources."onetime-5.1.2"
          sources."restore-cursor-4.0.0"
          sources."signal-exit-3.0.7"
          sources."string-width-7.2.0"
          sources."strip-ansi-7.1.0"
        ];
      })
      sources."os-tmpdir-1.0.2"
      sources."p-cancelable-3.0.0"
      sources."pac-proxy-agent-7.0.2"
      sources."pac-resolver-7.0.1"
      sources."package-json-8.1.1"
      sources."path-exists-5.0.0"
      sources."path-key-3.1.1"
      sources."picocolors-1.0.1"
      sources."proto-list-1.2.4"
      sources."proxy-agent-6.4.0"
      sources."proxy-from-env-1.1.0"
      sources."punycode-2.3.1"
      sources."pupa-3.1.0"
      sources."quick-lru-5.1.1"
      (sources."rc-1.2.8" // {
        dependencies = [
          sources."ini-1.3.8"
        ];
      })
      sources."readable-stream-3.6.2"
      sources."registry-auth-token-5.0.2"
      sources."registry-url-6.0.1"
      sources."require-from-string-2.0.2"
      sources."resolve-alpn-1.2.1"
      sources."responselike-3.0.0"
      (sources."restore-cursor-3.1.0" // {
        dependencies = [
          sources."mimic-fn-2.1.0"
          sources."onetime-5.1.2"
          sources."signal-exit-3.0.7"
        ];
      })
      sources."run-async-3.0.0"
      sources."rxjs-7.8.1"
      sources."safe-buffer-5.2.1"
      sources."safer-buffer-2.1.2"
      sources."semver-7.6.2"
      sources."semver-diff-4.0.0"
      sources."set-function-length-1.2.2"
      sources."shebang-command-2.0.0"
      sources."shebang-regex-3.0.0"
      sources."signal-exit-4.1.0"
      sources."smart-buffer-4.2.0"
      sources."socks-2.8.3"
      sources."socks-proxy-agent-8.0.4"
      sources."sprintf-js-1.1.3"
      sources."stdin-discarder-0.2.2"
      sources."string-width-4.2.3"
      sources."string_decoder-1.3.0"
      sources."strip-ansi-6.0.1"
      sources."strip-final-newline-3.0.0"
      sources."strip-json-comments-2.0.1"
      sources."stubborn-fs-1.2.5"
      sources."supports-color-7.2.0"
      sources."tmp-0.0.33"
      sources."tslib-2.6.3"
      sources."type-fest-3.13.1"
      sources."typedarray-to-buffer-3.1.5"
      sources."uint8array-extras-0.3.0"
      sources."unique-string-3.0.0"
      sources."universalify-2.0.1"
      sources."update-notifier-7.0.0"
      sources."uri-js-4.4.1"
      sources."util-deprecate-1.0.2"
      sources."validator-13.12.0"
      sources."wcwidth-1.0.1"
      sources."web-streams-polyfill-3.3.3"
      sources."when-exit-2.1.3"
      sources."which-2.0.2"
      (sources."widest-line-4.0.1" // {
        dependencies = [
          sources."ansi-regex-6.0.1"
          sources."emoji-regex-9.2.2"
          sources."string-width-5.1.2"
          sources."strip-ansi-7.1.0"
        ];
      })
      sources."wrap-ansi-6.2.0"
      (sources."write-file-atomic-3.0.3" // {
        dependencies = [
          sources."signal-exit-3.0.7"
        ];
      })
      sources."xdg-basedir-5.1.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
