on:
  pull_request:
    types:
      - labeled
name: Rebase
jobs:
  rebase:
    name: Rebase
    if: contains(github.event.pull_request.labels.*.name, 'rebase')
    runs-on: ubuntu-latest
    steps:
      - name: Remove "rebase" label
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          label: rebase
          type: remove
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
